# A Travis CI configuration file.

sudo: required

language: scala
scala:
   - 2.11.6
env:
  global:
    - secure: "cCDd/PfYpC5ndxwF/Tl3UUvYIQblPk2iugGIOO7RB0/iufrncn2vtmpo+CdVFS59bs5IpgNGj/gXcmilcQSMo4yuIXe1QGtUNp5oYtVg8/GALfpLsOawYfZ7Zz9oYhstz06R5epoCGJtzoQAwr9A8+o9W4gaDrHzVBiF1eNIYlyM3aDXfM3IiL5R2/DTWYhLqdKMFTPcx1us3EeAFJYS+ho2EAsxJI6o3kPdESzjhTOtksbetjzB2rWXyRCaRtpMsJXKTk5IhWJCi6/EsdAcy//HOUsUimWZHjgbZnRn5rOo5E4e324lIrzWPS9B9pETGm/jRsGmUso3FNfxBwEOi9Lp14InmpmiMOPXcAOAhPltizrrA/AYKrvzWdVQEMsylbkXYnEVTNKHx526x2dVl7sa8rrBjzpOUxnztsmfUlV4zsetCoubPg6beOQQ05wuiOm6omrxJ7RPrDB+Fi93wkzJEFjUASb/ogy9vYhTaUez8OCUzPLmPQDRwmY9fsnIl2nBpcZFsTXAu8nhPvrhezNYy7NfTxvglHPYuOqGRp+1AN8LNO6jHpGdd6rW1bWdAqjacwBsvdl6lNZeFSxcVzL67iViURiauMRQUnt/uJl6qMYotw57y5jhaitigmLl+J6k1Ab8shl3Vm8WCBab7FLDyrc7giobHZjYhcSOdJw="
    - secure: "jyY98VXK7W8vKEBx0/JTGOI0Xi0yPqFK7/SFG9j/iz0hgAeKrmXm1HJV6Cci1mpcEPhBqILYNuJGvFuyUWy1is0UCoVHtfrCbMon3Lh3pQarMEWbjjzdB6m51wogm+5ciDNBeQV9Eu4nhQfj3Yb6yu38utIcbAqhuVgM4E0iepuZYK9qkII2caoXnv2kO8RKggzSBarIT4jPvGlY30eejrEvAVRkvQBcgDIUaSX7XrpQCdry6fYwL0fO7hrOd90Q49FLPOkOtyMAQ69p2P8oc8JkZdyH59MPOqpgWszc9kiy7R4CKMCX1X1QAxiwFd84jsMi71kKbnyKtsD54H5Tmj3Ai6+Epzgd6Ey6JFycSQbWWsr16XV5e5wMUpXDMrY8vlmVIcikdVWFvRTR5pmWxAPq0Cx8PvxkCpDE31pevyEFRmbLqb4BxGN4LH1dUBL0bwknrALehSuJAS06M53284HUF0fiCSgY63E+sp+HyK1Y6R9qZeUXftxEGH0vovWYJ94NsqWa/+g4vGeFfhKPbnlK4+gVsTAHV1IRzCLIYTqdY/pFLoYyu6ZSVAvKzRRgyCerN48AUF4nTPuQtukU9d724Z6ZPsWi2i63HHsrDidqbnBWdbSFq9iljjbrGc23OWrDY3QwhHKcPn3Vn7WKuZcx71+Z/7GWLWaV4kGAHGg="
services:
  - docker

before_install:
  - ./tools/travis/setup.sh

install: true

script:
  - ./tools/travis/build.sh

deploy:
  # deploy latest
  - provider: script
    script: ./tools/travis/deploy.sh openwhisk cloudantprovider latest
    on:
      branch: master
  # deploy tag
  - provider: script
    script: ./tools/travis/deploy.sh openwhisk cloudantprovider $TRAVIS_TAG
    on:
      tags: true
      all_branches: true